### PR TITLE
Update max value for AFK countdown and timeout

### PR DESCRIPTION
**Pull request by pr0g**
## Relevant components:
- [ ] Signalling server
- [ ] Common library
- [X] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] Platform scripts
- [ ] SFU

## Problem statement:

This addresses an issue we've encountered where the AFK countdown and timeout delays are still too short.

## Solution

This PR bumps the max value supported for both AFK countdown and timeout.

## Documentation

N/A for this PR, the min/max values are not documented and documentation was added in the previous PR (see https://github.com/EpicGamesExt/PixelStreamingInfrastructure/pull/247).

## Test Plan and Compatibility

We plan to internally test this with our fork to ensure we can set longer timeouts.

## Additional

We would really appreciate if this change could be backported to `UE5.3-1` (similar to this release - https://github.com/EpicGamesExt/PixelStreamingInfrastructure/releases/tag/UE5.3-1.0.6). The diff for that version is slightly different (it's actually simpler) and looks like this:

```diff
diff --git a/Frontend/library/src/Config/Config.ts b/Frontend/library/src/Config/Config.ts
index cd02bb9..7402e6f 100644
--- a/Frontend/library/src/Config/Config.ts
+++ b/Frontend/library/src/Config/Config.ts
@@ -472,7 +472,7 @@ export class Config {
                 'AFK timeout',
                 'The time (in seconds) it takes for the application to time out if AFK timeout is enabled.',
                 0 /*min*/,
-                600 /*max*/,
+                3600 /*max*/,
                 120 /*value*/,
                 useUrlParams
             )
@@ -485,7 +485,7 @@ export class Config {
                 'AFK countdown',
                 'The time (in seconds) for a user to respond before the stream is ended after an AFK timeout.',
                 10 /*min*/,
-                180 /*max*/,
+                600 /*max*/,
                 10 /*value*/,
                 useUrlParams
             )
```

### CODE REVIEW

**Comment by mcottontensor** [comment]
This looks alright to me but I have a slightly different proposal.

I put up a new PR #288 which adds the ability to provide undefined for the min and max values and removes the limit for the AFK timers. So now users can set whatever value they need without limit.

Let me know if this works for you and ill back port it to the supported branches.

**Comment by pr0g** [comment]
Hi @mcottontensor, sorry I'm just getting back to you. 

Your proposal is a great idea! I think the PR looks excellent. My only minor suggestion would be it might make more sense to use `null` instead of `undefined` in this case as it implies an intentionally empty value instead of a missing one. It's a small semantic difference but might make the code slightly clearer.

Feel free to ignore my suggestion, the overall change looks great and it would be fantastic if you could backport it too.

Thank you very much for your help.

**Comment by mcottontensor** [comment]
Have merged #288 to master, UE5.2, UE5.3 and UE5.4 and pushed new releases for each branch. This should cover your case. Cheers.

**Comment by pr0g** [comment]
That's brilliant, @mcottontensor, thank you very much! 🙂

**Pull request closed without merging**
